title: Jonathan Alvarez - Especialista en Redes y Ciberseguridad
description: Portafolio profesional de Jonathan Alvarez, docente y especialista en redes, ciberseguridad y educación tecnológica

baseurl: "/portafoliojthn"  # Nombre exacto de tu repositorio
url: "https://jthnconti.github.io"

remote_theme: pages-themes/hacker@v0.2.0

static_files:
  - assets/
  - assets/css/
  - assets/images/

# Configuración esencial para plugins
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-feed


# Configuración de procesamiento
markdown: kramdown
highlighter: rouge
sass:
  style: compressed

# Configuración de datos
# Carga de datos
data_dir: "_data"

include:
  - "_data/education.json"
  - "_data/experience.json"
  - "_data/projects.json"
  - "_data/skills.json"

# Configuración personalizada
social:
  linkedin: jonathan-ac28
  email: jalvarezc@tecsup.edu.pe
  github: jthnconti

# Configuración específica para GitHub Pages
github: [metadata]