title: Jonathan Alvarez - Especialista en Redes y Ciberseguridad
description: Portafolio profesional de Jonathan Alvarez, docente y especialista en redes, ciberseguridad y educación tecnológica

baseurl: "" 
url: "https://jthnconti.github.io/portafoliojthn"

remote_theme: pages-themes/hacker@v0.2.0

static_files:
  - assets/
  - assets/css/
  - assets/images/

# Configuración esencial para plugins
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-data
  - jekyll-feed

# Configuración de defaults
defaults:
  - scope:
      path: ""  # Todos los archivos
    values:
      layout: default
  - scope:
      path: "_data"  # Archivos JSON son datos
    values:
      layout: null

# Configuración de procesamiento
markdown: kramdown
highlighter: rouge
sass:
  style: compressed

# Configuración de datos
data_source: "_data"
collections:
  data:
    output: false
    path: "_data"

include:
  - "_data/education.json"
  - "_data/experience.json"
  - "_data/projects.json"
  - "_data/skills.json"

# Configuración personalizada
social:
  linkedin: jonathan-ac28
  email: jalvarezc@tecsup.edu.pe
  github: jthnconti

# Configuración específica para GitHub Pages
github: [metadata]